export interface ExifTagType {
    exif: keyof typeof exifTags.exif;
    gps: keyof typeof exifTags.gps;
}
export const exifTags = {
    exif: new Map<number, string>([
        [0x0001, "InteroperabilityIndex"],
        [0x0002, "InteroperabilityVersion"],
        [0x000b, "ProcessingSoftware"],
        [0x00fe, "SubfileType"],
        [0x00ff, "OldSubfileType"],
        [0x0100, "ImageWidth"],
        [0x0101, "ImageHeight"],
        [0x0102, "BitsPerSample"],
        [0x0103, "Compression"],
        [0x0106, "PhotometricInterpretation"],
        [0x0107, "Thresholding"],
        [0x0108, "CellWidth"],
        [0x0109, "CellLength"],
        [0x010a, "FillOrder"],
        [0x010d, "DocumentName"],
        [0x010e, "ImageDescription"],
        [0x010f, "Make"],
        [0x0110, "Model"],
        [0x0111, "StripOffsets"],
        [0x0112, "Orientation"],
        [0x0115, "SamplesPerPixel"],
        [0x0116, "RowsPerStrip"],
        [0x0117, "StripByteCounts"],
        [0x0118, "MinSampleValue"],
        [0x0119, "MaxSampleValue"],
        [0x011a, "XResolution"],
        [0x011b, "YResolution"],
        [0x011c, "PlanarConfiguration"],
        [0x011d, "PageName"],
        [0x011e, "XPosition"],
        [0x011f, "YPosition"],
        [0x0120, "FreeOffsets"],
        [0x0121, "FreeByteCounts"],
        [0x0122, "GrayResponseUnit"],
        [0x0123, "GrayResponseCurve"],
        [0x0124, "T4Options"],
        [0x0125, "T6Options"],
        [0x0128, "ResolutionUnit"],
        [0x0129, "PageNumber"],
        [0x012c, "ColorResponseUnit"],
        [0x012d, "TransferFunction"],
        [0x0131, "Software"],
        [0x0132, "DateTime"],
        [0x013b, "Artist"],
        [0x013c, "HostComputer"],
        [0x013d, "Predictor"],
        [0x013e, "WhitePoint"],
        [0x013f, "PrimaryChromaticities"],
        [0x0140, "ColorMap"],
        [0x0141, "HalftoneHints"],
        [0x0142, "TileWidth"],
        [0x0143, "TileLength"],
        [0x0144, "TileOffsets"],
        [0x0145, "TileByteCounts"],
        [0x0146, "BadFaxLines"],
        [0x0147, "CleanFaxData"],
        [0x0148, "ConsecutiveBadFaxLines"],
        [0x014a, "SubIFD"],
        [0x014c, "InkSet"],
        [0x014d, "InkNames"],
        [0x014e, "NumberofInks"],
        [0x0150, "DotRange"],
        [0x0151, "TargetPrinter"],
        [0x0152, "ExtraSamples"],
        [0x0153, "SampleFormat"],
        [0x0154, "SMinSampleValue"],
        [0x0155, "SMaxSampleValue"],
        [0x0156, "TransferRange"],
        [0x0157, "ClipPath"],
        [0x0158, "XClipPathUnits"],
        [0x0159, "YClipPathUnits"],
        [0x015a, "Indexed"],
        [0x015b, "JPEGTables"],
        [0x015f, "OPIProxy"],
        [0x0190, "GlobalParametersIFD"],
        [0x0191, "ProfileType"],
        [0x0192, "FaxProfile"],
        [0x0193, "CodingMethods"],
        [0x0194, "VersionYear"],
        [0x0195, "ModeNumber"],
        [0x01b1, "Decode"],
        [0x01b2, "DefaultImageColor"],
        [0x01b3, "T82Options"],
        [0x01b5, "JPEGTables"],
        [0x0200, "JPEGProc"],
        [0x0201, "ThumbnailOffset"],
        [0x0202, "ThumbnailLength"],
        [0x0203, "JPEGRestartInterval"],
        [0x0205, "JPEGLosslessPredictors"],
        [0x0206, "JPEGPointTransforms"],
        [0x0207, "JPEGQTables"],
        [0x0208, "JPEGDCTables"],
        [0x0209, "JPEGACTables"],
        [0x0211, "YCbCrCoefficients"],
        [0x0212, "YCbCrSubSampling"],
        [0x0213, "YCbCrPositioning"],
        [0x0214, "ReferenceBlackWhite"],
        [0x022f, "StripRowCounts"],
        [0x02bc, "ApplicationNotes"],
        [0x03e7, "USPTOMiscellaneous"],
        [0x1000, "RelatedImageFileFormat"],
        [0x1001, "RelatedImageWidth"],
        [0x1002, "RelatedImageHeight"],
        [0x4746, "Rating"],
        [0x4747, "XP_DIP_XML"],
        [0x4748, "StitchInfo"],
        [0x4749, "RatingPercent"],
        [0x800d, "ImageID"],
        [0x80a3, "WangTag1"],
        [0x80a4, "WangAnnotation"],
        [0x80a5, "WangTag3"],
        [0x80a6, "WangTag4"],
        [0x80e3, "Matteing"],
        [0x80e4, "DataType"],
        [0x80e5, "ImageDepth"],
        [0x80e6, "TileDepth"],
        [0x827d, "Model2"],
        [0x828d, "CFARepeatPatternDim"],
        [0x828e, "CFAPattern2"],
        [0x828f, "BatteryLevel"],
        [0x8290, "KodakIFD"],
        [0x8298, "Copyright"],
        [0x829a, "ExposureTime"],
        [0x829d, "FNumber"],
        [0x82a5, "MDFileTag"],
        [0x82a6, "MDScalePixel"],
        [0x82a7, "MDColorTable"],
        [0x82a8, "MDLabName"],
        [0x82a9, "MDSampleInfo"],
        [0x82aa, "MDPrepDate"],
        [0x82ab, "MDPrepTime"],
        [0x82ac, "MDFileUnits"],
        [0x830e, "PixelScale"],
        [0x8335, "AdventScale"],
        [0x8336, "AdventRevision"],
        [0x835c, "UIC1Tag"],
        [0x835d, "UIC2Tag"],
        [0x835e, "UIC3Tag"],
        [0x835f, "UIC4Tag"],
        [0x83bb, "IPTC-NAA"],
        [0x847e, "IntergraphPacketData"],
        [0x847f, "IntergraphFlagRegisters"],
        [0x8480, "IntergraphMatrix"],
        [0x8481, "INGRReserved"],
        [0x8482, "ModelTiePoint"],
        [0x84e0, "Site"],
        [0x84e1, "ColorSequence"],
        [0x84e2, "IT8Header"],
        [0x84e3, "RasterPadding"],
        [0x84e4, "BitsPerRunLength"],
        [0x84e5, "BitsPerExtendedRunLength"],
        [0x84e6, "ColorTable"],
        [0x84e7, "ImageColorIndicator"],
        [0x84e8, "BackgroundColorIndicator"],
        [0x84e9, "ImageColorValue"],
        [0x84ea, "BackgroundColorValue"],
        [0x84eb, "PixelIntensityRange"],
        [0x84ec, "TransparencyIndicator"],
        [0x84ed, "ColorCharacterization"],
        [0x84ee, "HCUsage"],
        [0x84ef, "TrapIndicator"],
        [0x84f0, "CMYKEquivalent"],
        [0x8546, "SEMInfo"],
        [0x8568, "AFCP_IPTC"],
        [0x85b8, "PixelMagicJBIGOptions"],
        [0x85d8, "ModelTransform"],
        [0x8602, "WB_GRGBLevels"],
        [0x8606, "LeafData"],
        [0x8649, "PhotoshopSettings"],
        [0x8769, "ExifOffset"],
        [0x8773, "ICC_Profile"],
        [0x877f, "TIFF_FXExtensions"],
        [0x8780, "MultiProfiles"],
        [0x8781, "SharedData"],
        [0x8782, "T88Options"],
        [0x87ac, "ImageLayer"],
        [0x87af, "GeoTiffDirectory"],
        [0x87b0, "GeoTiffDoubleParams"],
        [0x87b1, "GeoTiffAsciiParams"],
        [0x8822, "ExposureProgram"],
        [0x8824, "SpectralSensitivity"],
        [0x8825, "GPSInfo"],
        [0x8827, "ISOSpeedRatings"],
        [0x8828, "Opto-ElectricConvFactor"],
        [0x8829, "Interlace"],
        [0x882a, "TimeZoneOffset"],
        [0x882b, "SelfTimerMode"],
        [0x8830, "SensitivityType"],
        [0x8831, "StandardOutputSensitivity"],
        [0x8832, "RecommendedExposureIndex"],
        [0x8833, "ISOSpeed"],
        [0x8834, "ISOSpeedLatitudeyyy"],
        [0x8835, "ISOSpeedLatitudezzz"],
        [0x885c, "FaxRecvParams"],
        [0x885d, "FaxSubAddress"],
        [0x885e, "FaxRecvTime"],
        [0x888a, "LeafSubIFD"],
        [0x9000, "ExifVersion"],
        [0x9003, "DateTimeOriginal"],
        [0x9004, "CreateDate"],
        [0x9101, "ComponentsConfiguration"],
        [0x9102, "CompressedBitsPerPixel"],
        [0x9201, "ShutterSpeedValue"],
        [0x9202, "ApertureValue"],
        [0x9203, "BrightnessValue"],
        [0x9204, "ExposureBiasValue"],
        [0x9205, "MaxApertureValue"],
        [0x9206, "SubjectDistance"],
        [0x9207, "MeteringMode"],
        [0x9208, "LightSource"],
        [0x9209, "Flash"],
        [0x920a, "FocalLength"],
        [0x920b, "FlashEnergy"],
        [0x920c, "SpatialFrequencyResponse"],
        [0x920d, "Noise"],
        [0x920e, "FocalPlaneXResolution"],
        [0x920f, "FocalPlaneYResolution"],
        [0x9210, "FocalPlaneResolutionUnit"],
        [0x9211, "ImageNumber"],
        [0x9212, "SecurityClassification"],
        [0x9213, "ImageHistory"],
        [0x9214, "SubjectArea"],
        [0x9215, "ExposureIndex"],
        [0x9216, "TIFF-EPStandardID"],
        [0x9217, "SensingMethod"],
        [0x923a, "CIP3DataFile"],
        [0x923b, "CIP3Sheet"],
        [0x923c, "CIP3Side"],
        [0x923f, "StoNits"],
        [0x927c, "MakerNote"],
        [0x9286, "UserComment"],
        [0x9290, "SubSecTime"],
        [0x9291, "SubSecTimeOriginal"],
        [0x9292, "SubSecTimeDigitized"],
        [0x932f, "MSDocumentText"],
        [0x9330, "MSPropertySetStorage"],
        [0x9331, "MSDocumentTextPosition"],
        [0x935c, "ImageSourceData"],
        [0x9c9b, "XPTitle"],
        [0x9c9c, "XPComment"],
        [0x9c9d, "XPAuthor"],
        [0x9c9e, "XPKeywords"],
        [0x9c9f, "XPSubject"],
        [0xa000, "FlashpixVersion"],
        [0xa001, "ColorSpace"],
        [0xa002, "PixelXDimension"],
        [0xa003, "PixelYDimension"],
        [0xa004, "RelatedSoundFile"],
        [0xa005, "InteropOffset"],
        [0xa20b, "FlashEnergy"],
        [0xa20c, "SpatialFrequencyResponse"],
        [0xa20d, "Noise"],
        [0xa20e, "FocalPlaneXResolution"],
        [0xa20f, "FocalPlaneYResolution"],
        [0xa210, "FocalPlaneResolutionUnit"],
        [0xa211, "ImageNumber"],
        [0xa212, "SecurityClassification"],
        [0xa213, "ImageHistory"],
        [0xa214, "SubjectLocation"],
        [0xa215, "ExposureIndex"],
        [0xa216, "TIFF-EPStandardID"],
        [0xa217, "SensingMethod"],
        [0xa300, "FileSource"],
        [0xa301, "SceneType"],
        [0xa302, "CFAPattern"],
        [0xa401, "CustomRendered"],
        [0xa402, "ExposureMode"],
        [0xa403, "WhiteBalance"],
        [0xa404, "DigitalZoomRatio"],
        [0xa405, "FocalLengthIn35mmFormat"],
        [0xa406, "SceneCaptureType"],
        [0xa407, "GainControl"],
        [0xa408, "Contrast"],
        [0xa409, "Saturation"],
        [0xa40a, "Sharpness"],
        [0xa40b, "DeviceSettingDescription"],
        [0xa40c, "SubjectDistanceRange"],
        [0xa420, "ImageUniqueID"],
        [0xa430, "OwnerName"],
        [0xa431, "SerialNumber"],
        [0xa432, "LensInfo"],
        [0xa433, "LensMake"],
        [0xa434, "LensModel"],
        [0xa435, "LensSerialNumber"],
        [0xa436, "Title"],
        [0xa437, "Photographer"],
        [0xa438, "ImageEditor"],
        [0xa439, "CameraFirmware"],
        [0xa43a, "RAWDevelopingSoftware"],
        [0xa43b, "ImageEditingSoftware"],
        [0xa43c, "MetadataEditingSoftware"],
        [0xa460, "CompositeImage"],
        [0xa461, "CompositeImageCount"],
        [0xa462, "CompositeImageExposureTimes"],
        [0xa480, "GDALMetadata"],
        [0xa481, "GDALNoData"],
        [0xa500, "Gamma"],
        [0xafc0, "ExpandSoftware"],
        [0xafc1, "ExpandLens"],
        [0xafc2, "ExpandFilm"],
        [0xafc3, "ExpandFilterLens"],
        [0xafc4, "ExpandScanner"],
        [0xafc5, "ExpandFlashLamp"],
        [0xbc01, "PixelFormat"],
        [0xbc02, "Transformation"],
        [0xbc03, "Uncompressed"],
        [0xbc04, "ImageType"],
        [0xbc80, "ImageWidth"],
        [0xbc81, "ImageHeight"],
        [0xbc82, "WidthResolution"],
        [0xbc83, "HeightResolution"],
        [0xbcc0, "ImageOffset"],
        [0xbcc1, "ImageByteCount"],
        [0xbcc2, "AlphaOffset"],
        [0xbcc3, "AlphaByteCount"],
        [0xbcc4, "ImageDataDiscard"],
        [0xbcc5, "AlphaDataDiscard"],
        [0xc427, "OceScanjobDesc"],
        [0xc428, "OceApplicationSelector"],
        [0xc429, "OceIDNumber"],
        [0xc42a, "OceImageLogic"],
        [0xc44f, "Annotations"],
        [0xc4a5, "PrintIM"],
        [0xc580, "USPTOOriginalContentType"],
        [0xc612, "DNGVersion"],
        [0xc613, "DNGBackwardVersion"],
        [0xc614, "UniqueCameraModel"],
        [0xc615, "LocalizedCameraModel"],
        [0xc616, "CFAPlaneColor"],
        [0xc617, "CFALayout"],
        [0xc618, "LinearizationTable"],
        [0xc619, "BlackLevelRepeatDim"],
        [0xc61a, "BlackLevel"],
        [0xc61b, "BlackLevelDeltaH"],
        [0xc61c, "BlackLevelDeltaV"],
        [0xc61d, "WhiteLevel"],
        [0xc61e, "DefaultScale"],
        [0xc61f, "DefaultCropOrigin"],
        [0xc620, "DefaultCropSize"],
        [0xc621, "ColorMatrix1"],
        [0xc622, "ColorMatrix2"],
        [0xc623, "CameraCalibration1"],
        [0xc624, "CameraCalibration2"],
        [0xc625, "ReductionMatrix1"],
        [0xc626, "ReductionMatrix2"],
        [0xc627, "AnalogBalance"],
        [0xc628, "AsShotNeutral"],
        [0xc629, "AsShotWhiteXY"],
        [0xc62a, "BaselineExposure"],
        [0xc62b, "BaselineNoise"],
        [0xc62c, "BaselineSharpness"],
        [0xc62d, "BayerGreenSplit"],
        [0xc62e, "LinearResponseLimit"],
        [0xc62f, "CameraSerialNumber"],
        [0xc630, "DNGLensInfo"],
        [0xc631, "ChromaBlurRadius"],
        [0xc632, "AntiAliasStrength"],
        [0xc633, "ShadowScale"],
        [0xc634, "DNGPrivateData"],
        [0xc635, "MakerNoteSafety"],
        [0xc640, "RawImageSegmentation"],
        [0xc65a, "CalibrationIlluminant1"],
        [0xc65b, "CalibrationIlluminant2"],
        [0xc65c, "BestQualityScale"],
        [0xc65d, "RawDataUniqueID"],
        [0xc660, "AliasLayerMetadata"],
        [0xc68b, "OriginalRawFileName"],
        [0xc68c, "OriginalRawFileData"],
        [0xc68d, "ActiveArea"],
        [0xc68e, "MaskedAreas"],
        [0xc68f, "AsShotICCProfile"],
        [0xc690, "AsShotPreProfileMatrix"],
        [0xc691, "CurrentICCProfile"],
        [0xc692, "CurrentPreProfileMatrix"],
        [0xc6bf, "ColorimetricReference"],
        [0xc6d2, "PanasonicTitle"],
        [0xc6d3, "PanasonicTitle2"],
        [0xc6f3, "CameraCalibrationSig"],
        [0xc6f4, "ProfileCalibrationSig"],
        [0xc6f5, "ProfileIFD"],
        [0xc6f6, "AsShotProfileName"],
        [0xc6f7, "NoiseReductionApplied"],
        [0xc6f8, "ProfileName"],
        [0xc6f9, "ProfileHueSatMapDims"],
        [0xc6fa, "ProfileHueSatMapData1"],
        [0xc6fb, "ProfileHueSatMapData2"],
        [0xc6fc, "ProfileToneCurve"],
        [0xc6fd, "ProfileEmbedPolicy"],
        [0xc6fe, "ProfileCopyright"],
        [0xc714, "ForwardMatrix1"],
        [0xc715, "ForwardMatrix2"],
        [0xc716, "PreviewApplicationName"],
        [0xc717, "PreviewApplicationVersion"],
        [0xc718, "PreviewSettingsName"],
        [0xc719, "PreviewSettingsDigest"],
        [0xc71a, "PreviewColorSpace"],
        [0xc71b, "PreviewDateTime"],
        [0xc71c, "RawImageDigest"],
        [0xc71d, "OriginalRawFileDigest"],
        [0xc71e, "SubTileBlockSize"],
        [0xc71f, "RowInterleaveFactor"],
        [0xc725, "ProfileLookTableDims"],
        [0xc726, "ProfileLookTableData"],
        [0xc740, "OpcodeList1"],
        [0xc741, "OpcodeList2"],
        [0xc74e, "OpcodeList3"],
        [0xc761, "NoiseProfile"],
        [0xc763, "TimeCodes"],
        [0xc764, "FrameRate"],
        [0xc772, "TStop"],
        [0xc789, "ReelName"],
        [0xc791, "OriginalDefaultFinalSize"],
        [0xc792, "OriginalBestQualitySize"],
        [0xc793, "OriginalDefaultCropSize"],
        [0xc7a1, "CameraLabel"],
        [0xc7a3, "ProfileHueSatMapEncoding"],
        [0xc7a4, "ProfileLookTableEncoding"],
        [0xc7a5, "BaselineExposureOffset"],
        [0xc7a6, "DefaultBlackRender"],
        [0xc7a7, "NewRawImageDigest"],
        [0xc7a8, "RawToPreviewGain"],
        [0xc7b5, "DefaultUserCrop"],
        [0xea1c, "Padding"],
        [0xea1d, "OffsetSchema"],
        [0xfde8, "OwnerName"],
        [0xfde9, "SerialNumber"],
        [0xfdea, "Lens"],
        [0xfe00, "KDC_IFD"],
        [0xfe4c, "RawFile"],
        [0xfe4d, "Converter"],
        [0xfe4e, "WhiteBalance"],
        [0xfe51, "Exposure"],
        [0xfe52, "Shadows"],
        [0xfe53, "Brightness"],
        [0xfe54, "Contrast"],
        [0xfe55, "Saturation"],
        [0xfe56, "Sharpness"],
        [0xfe57, "Smoothness"],
        [0xfe58, "MoireFilter"],
    ]),
    gps: new Map<number, string>([
        [0x0000, "GPSVersionID"],
        [0x0001, "GPSLatitudeRef"],
        [0x0002, "GPSLatitude"],
        [0x0003, "GPSLongitudeRef"],
        [0x0004, "GPSLongitude"],
        [0x0005, "GPSAltitudeRef"],
        [0x0006, "GPSAltitude"],
        [0x0007, "GPSTimeStamp"],
        [0x0008, "GPSSatellites"],
        [0x0009, "GPSStatus"],
        [0x000a, "GPSMeasureMode"],
        [0x000b, "GPSDOP"],
        [0x000c, "GPSSpeedRef"],
        [0x000d, "GPSSpeed"],
        [0x000e, "GPSTrackRef"],
        [0x000f, "GPSTrack"],
        [0x0010, "GPSImgDirectionRef"],
        [0x0011, "GPSImgDirection"],
        [0x0012, "GPSMapDatum"],
        [0x0013, "GPSDestLatitudeRef"],
        [0x0014, "GPSDestLatitude"],
        [0x0015, "GPSDestLongitudeRef"],
        [0x0016, "GPSDestLongitude"],
        [0x0017, "GPSDestBearingRef"],
        [0x0018, "GPSDestBearing"],
        [0x0019, "GPSDestDistanceRef"],
        [0x001a, "GPSDestDistance"],
        [0x001b, "GPSProcessingMethod"],
        [0x001c, "GPSAreaInformation"],
        [0x001d, "GPSDateStamp"],
        [0x001e, "GPSDifferential"],
        [0x001f, "GPSHPositioningError"],
    ]),
};

export enum ExifSections {
    Image = 1,
    Thumbnail = 2,
    GPS = 3,
    Interop = 4,
    EXIF = 5,
}

enum ExifResolutionUnit {
    None = 1,
    Inch = 2,
    Centimeter = 3,
}

enum ExifImageAdjustmentLevel {
    Normal = 0,
    Soft = 1,
    Hard = 2,
}

enum ExifLightSource {
    "Unknown" = 0,
    "Daylight" = 1,
    "Fluorescent" = 2,
    "Tungsten incandescent light" = 3,
    "Flash" = 4,
    "Fine weather" = 9,
    "Cloudy weather" = 10,
    "Shade" = 11,
    "Daylight fluorescent" = 12,
    "Day white fluorescent" = 13,
    "Cool white fluorescent" = 14,
    "White fluorescent" = 15,
    "Standard light A" = 17,
    "Standard light B" = 18,
    "Standard light C" = 19,
    "D55" = 20,
    "D65" = 21,
    "D75" = 22,
    "ISO studio tungsten" = 24,
    "Other" = 255,
}

enum ExifSensingMethod {
    "Not defined" = 1,
    "One-chip color area sensor" = 2,
    "Two-chip color area sensor" = 3,
    "Three-chip color area sensor" = 4,
    "Color sequential area sensor" = 5,
    "Trilinear sensor" = 7,
    "Color sequential linear sensor" = 8,
}

enum ExifMeteringMode {
    "Unknown" = 0,
    "Average" = 1,
    "Center-weighted average" = 2,
    "Spot" = 3,
    "Multi spot" = 4,
    "Pattern" = 5,
    "Partial" = 6,
    "Other" = 255,
}

enum ExifColorSpace {
    "sRGB" = 1,
    "Adobe RGB" = 2,
    "Uncalibrated" = 65535,
}

enum ExifCompositeImage {
    "Unknown" = 0,
    "No a composite image" = 1,
    "General composite image" = 2,
    "Composite image captured while shooting" = 3,
}

enum ExifOrientation {
    "Top-left" = 1,
    "Top-right" = 2,
    "Bottom-right" = 3,
    "Bottom-left" = 4,
    "Left-top" = 5,
    "Right-top" = 6,
    "Right-bottom" = 7,
    "Left-bottom" = 8,
}

enum ExifExposureMode {
    "Auto exposure" = 0,
    "Manual exposure" = 1,
    "Auto bracket" = 2,
}
enum ExifExposureProgram {
    "Not defined" = 0,
    "Manual" = 1,
    "Normal program" = 2,
    "Aperture priority" = 3,
    "Shutter priority" = 4,
    "Creative program (biased toward depth of field)" = 5,
    "Creative program (biased toward fast shutter speed)" = 6,
    "Portrait mode (for closeup photos with the background out of focus)" = 7,
    "Landscape mode (for landscape photos with the background in focus)" = 8,
}

enum ExifSensitivityType {
    "Unknown" = 0,
    "Standard output sensitivity (SOS)" = 1,
    "Recommended exposure index (REI)" = 2,
    "ISO speed" = 3,
    "Standard output sensitivity (SOS) and recommended exposure index (REI)" = 4,
    "Standard output sensitivity (SOS) and ISO speed" = 5,
    "Recommended exposure index (REI) and ISO speed" = 6,
    "Standard output sensitivity (SOS) and recommended exposure index (REI) and ISO speed" = 7,
}

enum ExifWhiteBalance {
    "Auto white balance" = 0,
    "Manual white balance" = 1,
}

enum ExifGainControl {
    "Normal" = 0,
    "Low gain up" = 1,
    "High gain Up" = 2,
    "Low gain down" = 3,
    "High gain down" = 4,
}

enum ExifCustomRendered {
    "Normal process" = 0,
    "Custom process" = 1,
}

enum ExifCompression {
    "Uncompressed" = 1,
    "CCITT 1D" = 2,
    "T4/Group 3 Fax" = 3,
    "T6/Group 4 Fax" = 4,
    "LZW compression" = 5,
    "JPEG compression" = 6,
    "JPEG compression (new)" = 7,
    "Deflate/ZIP compression" = 8,
    "JBIG B&W" = 9,
    "JBIG Color" = 10,
    "JPEG" = 99,
    "Next" = 32766,
    "Sony ARW Compressed" = 32767,
    "Packed RAW" = 32769,
    "Samsung SRW Compressed" = 32770,
    "CCIRLEW" = 32771,
    "Samsung SRW Compressed 2" = 32772,
    "PackBits compression" = 32773,
    "Thunderscan" = 32809,
    "Kodak KDC Compressed" = 32867,
    "IT8CTPAD" = 32895,
    "IT8LW" = 32896,
    "IT8MP" = 32897,
    "IT8BL" = 32898,
    "PixarFilm" = 32908,
    "PixarLog" = 32909,
    "Deflate" = 32946,
    "DCS" = 32947,
    "Aperio JPEG 2000 YCbCr" = 33003,
    "Aperio JPEG 2000 RGB" = 33005,
    "JBIG" = 34661,
    "SGILog" = 34676,
    "SGILog24" = 34677,
    "JPEG 2000" = 34712,
    "Nikon NEF Compressed" = 34713,
    "JBIG2 TIFF FX" = 34715,
    "Microsoft Document Imaging (MDI) Binary Level Codec" = 34718,
    "Microsoft Document Imaging (MDI) Progressive Transform Codec" = 34719,
    "Microsoft Document Imaging (MDI) Vector" = 34720,
    "ESRI Lerc" = 34887,
    "Lossy JPEG" = 34892,
    "LZMA2" = 34925,
    "Zstd" = 34926,
    "WebP" = 34927,
    "PNG" = 34933,
    "JPEG XR" = 34934,
    "JPEG XL" = 52546,
    "Kodak DCR Compressed" = 65000,
    "Pentax PEF Compressed" = 65535,
}

enum ExifFlash {
    "Flash did not fire" = 0x0,
    "Flash fired" = 0x1,
    "Strobe return light not detected" = 0x5,
    "Strobe return light detected" = 0x7,
    "Flash fired, compulsory flash mode" = 0x9,
    "Flash fired, compulsory flash mode, return light not detected" = 0xd,
    "Flash fired, compulsory flash mode, return light detected" = 0xf,
    "Flash did not fire, compulsory flash mode" = 0x10,
    "Flash did not fire, auto mode" = 0x18,
    "Flash fired, auto mode" = 0x19,
    "Flash fired, auto mode, return light not detected" = 0x1d,
    "Flash fired, auto mode, return light detected" = 0x1f,
    "No flash function" = 0x20,
    "Flash fired, red-eye reduction mode" = 0x41,
    "Flash fired, red-eye reduction mode, return light not detected" = 0x45,
    "Flash fired, red-eye reduction mode, return light detected" = 0x47,
    "Flash fired, compulsory flash mode, red-eye reduction mode" = 0x49,
    "Flash fired, compulsory flash mode, red-eye reduction mode, return light not detected" = 0x4d,
    "Flash fired, compulsory flash mode, red-eye reduction mode, return light detected" = 0x4f,
    "Flash fired, auto mode, red-eye reduction mode" = 0x59,
    "Flash fired, auto mode, return light not detected, red-eye reduction mode" = 0x5d,
    "Flash fired, auto mode, return light detected, red-eye reduction mode" = 0x5f,
}

enum ExifSubjectDistanceRange {
    "Unknown" = 0,
    "Macro" = 1,
    "Close view" = 2,
    "Distant view" = 3,
}

enum ExifYCbCrPositioning {
    "Centered" = 1,
    "Co-sited" = 2,
}

enum ExifPhotometricInterpretation {
    "Reversed mono" = 0,
    "Normal mono" = 1,
    "RGB" = 2,
    "Palette" = 3,
    "CMYK" = 5,
    "YCbCr" = 6,
    "CieLAB" = 8,
}

enum ExifSceneCaptureType {
    "Standard" = 0,
    "Landscape" = 1,
    "Portrait" = 2,
    "Night scene" = 3,
}

enum ExifGPSAltitudeRef {
    "Sea level" = 0,
    "Sea level reference" = 1,
}
enum ExifGPSMeasureMode {
    "2-dimensional measurement" = 2,
    "3-dimensional measurement" = 3,
}

enum ExifGPSDifferential {
    "No differential correction" = 0,
    "Differential corrected" = 1,
}

enum ExifGPSStatus {
    "Measurement active" = "A",
    "Measurement void" = "V",
}

export interface ExifTagEnums {
    [key: string]: any;
}

export const exifTagEnums: ExifTagEnums = {
    ColorSpace: ExifColorSpace,
    Compression: ExifCompression,
    Flash: ExifFlash,
    LightSource: ExifLightSource,
    Contrast: ExifImageAdjustmentLevel,
    Saturation: ExifImageAdjustmentLevel,
    Sharpness: ExifImageAdjustmentLevel,
    GainControl: ExifGainControl,
    ExposureMode: ExifExposureMode,
    ExposureProgram: ExifExposureProgram,
    SensitivityType: ExifSensitivityType,
    PhotometricInterpretation: ExifPhotometricInterpretation,
    CompositeImage: ExifCompositeImage,
    WhiteBalance: ExifWhiteBalance,
    SceneCaptureType: ExifSceneCaptureType,
    SubjectDistanceRange: ExifSubjectDistanceRange,
    SensingMethod: ExifSensingMethod,
    MeteringMode: ExifMeteringMode,
    Orientation: ExifOrientation,
    ResolutionUnit: ExifResolutionUnit,
    FocalPlaneResolutionUnit: ExifResolutionUnit,
    CustomRendered: ExifCustomRendered,
    YCbCrPositioning: ExifYCbCrPositioning,
    GPSAltitudeRef: ExifGPSAltitudeRef,
    GPSMeasureMode: ExifGPSMeasureMode,
    GPSDifferential: ExifGPSDifferential,
    GPSStatus: ExifGPSStatus,
};
