import { BrsValue, ValueKind, BrsString, BrsBoolean } from "../BrsType";
import { BrsComponent } from "./BrsComponent";
import { BrsType } from "..";
import { Callable } from "../Callable";
import { Interpreter } from "../../interpreter";
import { Int32 } from "../Int32";

export class RoUniversalControlEvent extends BrsComponent implements BrsValue {
    readonly kind = ValueKind.Object;
    private key: number;
    private remote: string;
    private mod: number;

    constructor(remote: string, key: number, mod: number) {
        super("roUniversalControlEvent");
        this.key = key;
        this.remote = remote;
        this.mod = mod;

        this.registerMethods({
            ifUniversalControlEvent: [
                this.getInt,
                this.getKey,
                this.getRemoteID,
                this.getID,
                this.isPress,
                this.getChar,
            ],
        });
    }

    toString(parent?: BrsType): string {
        return "<Component: roUniversalControlEvent>";
    }

    equalTo(other: BrsType) {
        return BrsBoolean.False;
    }

    /** Returns an integer representing pressed or released keys on the remote. */
    private getInt = new Callable("getInt", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            return new Int32(this.key);
        },
    });

    /** Returns the ID of the remote button that generated an event. */
    private getKey = new Callable("getKey", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            let id = this.key - this.mod;
            if (id >= 32) {
                id = 0;
            }
            return new Int32(id);
        },
    });

    /** Returns the ID of the remote button or character value represented by the event. */
    private getID = new Callable("getID", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            return new Int32(this.key - this.mod);
        },
    });

    /** Returns an identifier associated with the type and ID of the remote control that generated the event. */
    private getRemoteID = new Callable("getRemoteID", {
        signature: {
            args: [],
            returns: ValueKind.String,
        },
        impl: (_: Interpreter) => {
            return new BrsString(this.remote);
        },
    });

    /** Returns the Unicode character value generated by a keyboard key press event. */
    private getChar = new Callable("getChar", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            let char = this.key - this.mod;
            if (char < 32) {
                char = 0;
            }
            return new Int32(char);
        },
    });

    /** Returns true if there is a press event; false otherwise. */
    private isPress = new Callable("isPress", {
        signature: {
            args: [],
            returns: ValueKind.Boolean,
        },
        impl: (_: Interpreter) => {
            return BrsBoolean.from(this.mod < 100);
        },
    });
}
