sub Main()
    date = CreateObject("roDateTime")
    print "Today: " date.getYear().toStr() + "-" + date.getMonth().toStr() + "-" + date.getDayOfMonth().toStr()
    date.fromISO8601String("2010-11-12T13:14:15.160")
    print "No Param: " date.AsDateStringNoParam()
    print "Long Date: " date.AsDateString("long-date")
    print "Short Week Day: " date.AsDateString("short-weekday")
    print "No Week Day: " date.AsDateString("no-weekday")
    print "Short Month: " date.AsDateString("short-month")
    print "Short Month Short Weekday: " date.AsDateString("short-month-short-weekday")
    print "Short Month No Weekday: " date.AsDateString("short-month-no-weekday")
    print "Short Date: " date.AsDateString("short-date")
    print "Short Date Dashes: " date.AsDateString("short-date-dashes")
    print "Weekday: " date.getWeekday()
    print "Day of Week: " date.getDayOfWeek()
    print "Day of Month: " date.getDayOfMonth()
    print "Month: " date.getMonth()
    print "Year: " date.getYear()
    print "Hours: " date.getHours()
    print "Minutes: " date.getMinutes()
    print "Seconds: " date.getSeconds()
    print "Last Day of Month: " date.getLastDayOfMonth()
    print "Milliseconds: " date.getMilliseconds()
    print "ISO String UTC: " date.toISOString()
    print "ISO String UTC with milliseconds: " date.toISOString("milliseconds")
    print "Empty Format: " date.AsDateString("")
    print "Invalid Format: " date.AsDateString("invalid")
    print "------ New asDateStringLoc ------"
    print "DateLoc - full: " date.asDateStringLoc("full")
    print "DateLoc - long: " date.asDateStringLoc("long")
    print "DateLoc - medium: " date.asDateStringLoc("medium")
    print "DateLoc - short: " date.asDateStringLoc("short")
    print "DateLoc - custom: " date.asDateStringLoc("dd:MMMM:yy")
    print "DateLoc - custom: " date.asDateStringLoc("MM.EEE/y")
    print "DateLoc - custom: " date.asDateStringLoc("BeforeMM.EEE/y")
    print "DateLoc - custom: " date.asDateStringLoc("MM.EEE/yAfter")
    print "DateLoc - EMMANUEL: " date.asDateStringLoc("E MM ANUEL")
    print "DateLoc - EMMANUEL: " date.asDateStringLoc("EMMANUEL")
    print "DateLoc - invalid: " date.asDateStringLoc("something")
    print "------ New asTimeStringLoc ------"
    print "TimeLoc - short: " date.asTimeStringLoc("short")
    print "TimeLoc - short-h12: " date.asTimeStringLoc("short-h12")
    print "TimeLoc - short-h24: " date.asTimeStringLoc("short-h24")
    print "TimeLoc - custom: " date.asTimeStringLoc("h a")
    print "TimeLoc - custom: " date.asTimeStringLoc("H a")
    print "TimeLoc - empty: " date.asTimeStringLoc("")
    print "TimeLoc - no seconds: " date.asTimeStringLoc("h:mm:ss a")
    print "------ New Long Integer support ------"
    date.FromSeconds(2550877200)
    print date.toISOString()
    date.FromSeconds(2550877200&)
    print date.toISOString()
    date.FromSecondsLong(2550877200)
    print date.toISOString()
    print date.asSeconds()
    print date.asSecondsLong()
    print date.asMillisecondsLong()
end sub
