import {
    BrsType,
    ValueKind,
    BrsString,
    BrsBoolean,
    Int32,
    Float,
    Callable,
    Comparable,
    isNumberComp,
    StdlibArgument,
} from "..";
import { BrsEvent } from "./BrsEvent";
import { Interpreter } from "../../interpreter";
import { KeyEvent } from "../../common";
import { BrsDevice } from "../../device/BrsDevice";

export class RoUniversalControlEvent extends BrsEvent implements Comparable {
    private readonly event: KeyEvent;
    constructor(keyEvent: KeyEvent) {
        super("roUniversalControlEvent");
        this.event = keyEvent;

        this.registerMethods({
            ifUniversalControlEvent: [
                this.getKey,
                this.getRemoteID,
                this.getID,
                this.isPress,
                this.getChar,
                this.getFloatValue,
            ],
            ifInt: [this.getInt],
        });
    }

    toString(_parent?: BrsType): string {
        return this.event.key.toString();
    }

    getValue(): number {
        return this.event.key;
    }

    lessThan(other: BrsType): BrsBoolean {
        if (other.kind === ValueKind.Int64) {
            return BrsBoolean.from(this.getValue() < other.getValue().toNumber());
        } else if (isNumberComp(other)) {
            return BrsBoolean.from(this.getValue() < other.getValue());
        }
        return BrsBoolean.False;
    }

    greaterThan(other: BrsType): BrsBoolean {
        if (other.kind === ValueKind.Int64) {
            return BrsBoolean.from(this.getValue() > other.getValue().toNumber());
        } else if (isNumberComp(other)) {
            return BrsBoolean.from(this.getValue() > other.getValue());
        }
        return BrsBoolean.False;
    }

    equalTo(other: BrsType): BrsBoolean {
        if (other.kind === ValueKind.Int64) {
            return BrsBoolean.from(this.getValue() === other.getValue().toNumber());
        } else if (isNumberComp(other)) {
            return BrsBoolean.from(this.getValue() === other.getValue());
        }
        return BrsBoolean.False;
    }

    /** Returns an integer representing pressed or released keys on the remote. */
    private readonly getInt = new Callable("getInt", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            return new Int32(this.event.key);
        },
    });

    /** Returns the ID of the remote button that generated an event. */
    private readonly getKey = new Callable("getKey", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            let id = this.event.key - this.event.mod;
            if (id >= 32) {
                id = 0;
            }
            return new Int32(id);
        },
    });

    /** Returns the ID of the remote button or character value represented by the event. */
    private readonly getID = new Callable("getID", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            return new Int32(this.event.key - this.event.mod);
        },
    });

    /** Returns an identifier associated with the type and ID of the remote control that generated the event. */
    private readonly getRemoteID = new Callable("getRemoteID", {
        signature: {
            args: [],
            returns: ValueKind.String,
        },
        impl: (_: Interpreter) => {
            return new BrsString(this.event.remote);
        },
    });

    /** Returns the Unicode character value generated by a keyboard key press event. */
    private readonly getChar = new Callable("getChar", {
        signature: {
            args: [],
            returns: ValueKind.Int32,
        },
        impl: (_: Interpreter) => {
            let char = this.event.key - this.event.mod;
            if (char < 32) {
                char = 0;
            }
            return new Int32(char);
        },
    });

    /** Returns true if there is a press event; false otherwise. */
    private readonly isPress = new Callable("isPress", {
        signature: {
            args: [],
            returns: ValueKind.Boolean,
        },
        impl: (_: Interpreter) => {
            return BrsBoolean.from(this.event.mod < 100);
        },
    });

    /**
     * [brs-engine extension - no equivalent on real Roku hardware] Returns the live analog value
     * for `axis` (see AnalogAxis in src/core/common.ts: 0=LeftX, 1=LeftY, 2=RightX, 3=RightY,
     * 4=LeftTrigger, 5=RightTrigger), in the range [-1,1] for sticks or [0,1] for triggers. Only
     * populated when the app manifest sets `multi_controllers=1` and this event's remote is a
     * tracked Bluetooth gamepad; otherwise falls back to 1.0/0.0 based on IsPress(), matching
     * Roku's digital-only semantics for discrete buttons/DPad.
     */
    private readonly getFloatValue = new Callable("getvalue", {
        signature: {
            args: [new StdlibArgument("axis", ValueKind.Int32)],
            returns: ValueKind.Float,
        },
        impl: (_: Interpreter, axis: Int32) => {
            const analog = BrsDevice.getAnalogValue(this.event.remote, axis.getValue());
            return new Float(analog ?? (this.event.mod < 100 ? 1 : 0));
        },
    });
}
